apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app1
  labels:
    app: spring-boot-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app1
  template:
    metadata:
      labels:
        app: spring-boot-app1
    spec:
      containers:
      - name: spring-boot-app
        image: abhishekf5/ultimate-cicd:35
        ports:
        - containerPort: 8080
